version: '2'
services:
  influxdb:
    restart: always
    image: rem/rpi-influxdb
    volumes:
      - /opt/influxdb:/influxdb
    ports:
      - 8086:8086

  grafana:
    restart: always
    image: heziegl/rpi-grafana:3.1.1
    ports:
      - 3000:3000
    volumes:
      - /opt/grafana/etc:/etc/grafana
      - /opt/grafana/data:/data
    depends_on:
      - influxdb

  dataservice:
    restart: always
    image: rem/dataservice
    environment:
      - INFLUXDB_DATABASE=energy
      - INFLUXDB_HOST=influxdb:8086
    depends_on:
      - influxdb
    ports:
      - 8080

  vcontrold:
    restart: always
    image: rem/vcontrold
    devices:
      - /dev/ttyUSB1
    ports:
     - 3002

  acquisition:
    restart: always
    image: rem/acquisition
    environment:
      - DATASERVICE_HOST=dataservice:8080
    depends_on:
      - dataservice
    privileged: true
    volumes:
      - /sys/class/gpio/:/sys/class/gpio/

  temperature:
    restart: always
    image: rem/temperature
    environment:
      - DATASERVICE_HOST=dataservice:8080
    depends_on:
      - dataservice

  vcontrol:
    restart: always
    image: rem/vcontrol
    environment:
      - DATASERVICE_HOST=dataservice:8080
    depends_on:
      - dataservice

  display:
    restart: always
    image: rem/display
    environment:
      - DATASERVICE_HOST=dataservice:8080
    depends_on:
      - dataservice
    privileged: true
    volumes:
      - /dev/fb1:/dev/fb1
      - /dev/input/touchscreen:/dev/input/touchscreen

