version: '2'
services:

  acquisition:
    restart: always
    image: rem/acquisition
    environment:
      - DATASERVICE_HOST=192.168.2.100:8080
    privileged: true
    volumes:
      - /sys/class/gpio/:/sys/class/gpio/

  temperature:
    restart: always
    image: rem/temperature
    dns: 192.168.2.1
    environment:
      - DATASERVICE_HOST=192.168.2.100:8080

  display:
    restart: always
    image: rem/display
    privileged: true
    environment:
      - DATASERVICE_HOST=192.168.2.100:8080
    volumes:
      - /dev/fb1:/dev/fb1
      - /dev/input/touchscreen:/dev/input/touchscreen

